/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
#include <iostream>
#include <boost/xpressive/xpressive.hpp>

using namespace boost::xpressive;

/* Header for class org_pointclouds_PCLAndroidSample_HelloPCL */

#ifndef _Included_com_theveganrobot_cmake_HelloBoost
#define _Included_com_theveganrobot_cmake_HelloBoost
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     org_pointclouds_PCLAndroidSample_HelloPCL
	 * Method:    boostMkDir
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jint JNICALL Java_tw_com_hellopcl_MainActivity_boostMkDir
  (JNIEnv *, jobject);

	/*
	 * Class:     org_pointclouds_PCLAndroidSample_HelloPCL
	 * Method:    smoothPointCloud
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_tw_com_hellopcl_MainActivity_smoothPointCloud
  (JNIEnv *, jobject);
	
	
	
#ifdef __cplusplus
}
#endif
#endif
